# Docker
# Build and push images to Azure Container Registry

trigger:
  paths:
    include:
      - vote/*
      - result/*
      - worker/*

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: '774bd28a-0ff8-4bb1-8235-002f2aa7b24e'

  dockerfilePathvote: '$(Build.SourcesDirectory)/vote/Dockerfile'
  dockerfilePathresult: '$(Build.SourcesDirectory)/result/Dockerfile'
  dockerfilePathworker: '$(Build.SourcesDirectory)/worker/Dockerfile'

  tag: '$(Build.BuildId)'

pool:
  name: 'SelfHosted-ec2'

stages:
- stage: BuildImages
  displayName: Build and Push Images

  jobs:

  - job: BuildVote
    displayName: Build Vote Image
    steps:
    - task: Docker@2
      displayName: Build and Push Vote Image
      inputs:
        command: buildAndPush
        repository: votingapp/vote
        dockerfile: $(dockerfilePathvote)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

  - job: BuildResult
    displayName: Build Result Image
    steps:
    - task: Docker@2
      displayName: Build and Push Result Image
      inputs:
        command: buildAndPush
        repository: votingapp/result
        dockerfile: $(dockerfilePathresult)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

  - job: BuildWorker
    displayName: Build Worker Image
    steps:
    - task: Docker@2
      displayName: Build and Push Worker Image
      inputs:
        command: buildAndPush
        repository: votingapp/worker
        dockerfile: $(dockerfilePathworker)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)