apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devboard-intern-role-binding
  namespace: devboard
subjects:
- kind: ServiceAccount
  name: devboard-intern
  namespace: devboard
roleRef:
  kind: Role
  name: devboard-intern-role
  apiGroup: rbac.authorization.k8s.io