name: Go Linter

on:
  workflow_dispatch:

jobs:
    code-format:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                go: ['1.25', '1.26']
        steps:
            - name: Code Checkout
              uses: actions/checkout@v7

            - name: Setup Go
              uses: actions/setup-go@v6
              with:
                go-version: ${{ matrix.go }}
                cache-dependency-path: backend/go.sum

            - name: Run Go Formatter
              run: go fmt ./...
              working-directory: backend

            - name: Run Go Vet
              run: go vet ./...
              working-directory: backend
