name: Sonar Scan

on:
    workflow_call:

jobs:
    sonar-scanner:
        runs-on: ubuntu-latest
        steps:
            - name: Code Checkout
              uses: actions/checkout@v7
              with:
                fetch-depth: 0

            - name: SonarCloud Scan
              continue-on-error: true
              uses: SonarSource/sonarqube-scan-action@v8.2.0
              env:
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}