{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: devboard-secrets
  labels:
    {{- include "devboard.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}

  secretStoreRef:
    name: {{ .Values.externalSecrets.storeName }}
    kind: ClusterSecretStore

  target:
    name: devboard-secrets
    creationPolicy: Owner
    deletionPolicy: Delete

    template:
      engineVersion: v2
      type: Opaque
      data:
        POSTGRES_USER: "{{ `{{ .username }}` }}"
        POSTGRES_PASSWORD: "{{ `{{ .password }}` }}"
        POSTGRES_DB: "{{ `{{ .dbname }}` }}"
        POSTGRES_URL: "postgres://{{ `{{ .username }}` }}:{{ `{{ .password }}` }}@{{ .Values.postgres.serviceName }}:5432/{{ `{{ .dbname }}` }}?sslmode=disable"

  dataFrom:
    - extract:
        key: {{ .Values.externalSecrets.secretKey }}
{{- end }}
