apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "devboard.fullname" . }}-frontend
  labels:
    {{- include "devboard.labels" . | nindent 4 }}
    app: devboard-frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: devboard-frontend
  template:
    metadata:
      labels:
        {{- include "devboard.labels" . | nindent 8 }}
        app: devboard-frontend
    spec:
      containers:
        - name: devboard-frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.containerPort }}
            initialDelaySeconds: 15
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.containerPort }}
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
