apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: devboard-secrets
  namespace: devboard
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore

  target:
    name: devboard-secrets
    creationPolicy: Owner
    deletionPolicy: Delete

    template:
      engineVersion: v2
      type: Opaque
      data:
        POSTGRES_USER: "{{ .username }}"
        POSTGRES_PASSWORD: "{{ .password }}"
        POSTGRES_DB: "{{ .dbname }}"
        POSTGRES_URL: "postgres://{{ .username }}:{{ .password }}@postgres:5432/{{ .dbname }}?sslmode=disable"

  dataFrom:
    - extract:
        key: devboard/postgres
